/** Condensed print view (1–2 Letter pages), served as raw HTML for the PDF renderer. */
import { NextRequest, NextResponse } from "next/server";
import { getReport } from "@/lib/jobs";
import type { Verdict } from "@/lib/types";

export const dynamic = "force-dynamic";

const COLOR: Record<Verdict, string> = { pass: "#1f5c1f", fail: "#9b1c1c", "needs-review": "#7a5b00" };
const WORD: Record<Verdict, string> = { pass: "Pass", fail: "Fail", "needs-review": "Review" };

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  const report = getReport(id);
  if (!report) return NextResponse.json({ error: "Unknown report id." }, { status: 404 });

  const [lo, hi] = report.band.map((v) => Math.round(v * 100));
  const actionable = report.criteria.filter((c) => c.verdict !== "pass");
  const passed = report.criteria.length - actionable.length;
  const rows = actionable.map((c) => `
      <tr>
        <td style="color:${COLOR[c.verdict]};font-weight:700">${WORD[c.verdict]}</td>
        <td><strong>${c.criterionId}</strong> ${esc(c.name)}</td>
        <td>${c.level}</td>
        <td>${Math.round(c.confidence * 100)}%</td>
        <td>${esc(c.detail.slice(0, 220))}${c.detail.length > 220 ? "…" : ""}</td>
      </tr>`).join("");
  const axeTotal = report.axeSummary.violations + report.axeSummary.passes + report.axeSummary.incomplete;
  const axeBit = axeTotal > 0
    ? `(${report.axeSummary.violations} violations, ${report.axeSummary.incomplete} incomplete, ${report.axeSummary.passes} passed)`
    : "";

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>WCAG Audit — ${esc(report.finalUrl)}</title>
<style>
  @page { size: Letter; margin: 14mm 12mm; }
  body { font-family: system-ui, sans-serif; color: #1b1b1b; font-size: 11px; line-height: 1.35; margin: 0; }
  h1 { font-size: 20px; margin: 0 0 2px; }
  h2 { font-size: 13px; margin: 14px 0 6px; border-bottom: 1px solid #999; padding-bottom: 3px; }
  .meta { color: #444; font-size: 10px; margin-bottom: 8px; }
  .score { display: flex; gap: 16px; align-items: center; margin: 8px 0; }
  .score .n { font-size: 34px; font-weight: 800; }
  table { width: 100%; border-collapse: collapse; font-size: 10px; }
  th { text-align: left; border-bottom: 1px solid #666; padding: 3px 6px 3px 0; }
  td { border-bottom: 1px solid #ddd; padding: 3px 6px 3px 0; vertical-align: top; }
  .foot { margin-top: 10px; font-size: 9px; color: #555; }
</style></head>
<body>
  <h1>WCAG Accessibility Audit</h1>
  <div class="meta">${esc(report.finalUrl)} · ${esc(new Date(report.finishedAt).toLocaleString())}<br>
  Standards: ${esc(report.standardsApplied.join(", "))}${report.lawsApplied.length > 0 ? ` · Laws: ${esc(report.lawsApplied.map((l) => l.name).join("; "))}` : ""}</div>
  <div class="score"><div class="n">${Math.round(report.score * 100)}%</div>
  <div>of ${report.criteria.length} checked criteria pass (${passed} pass, ${report.counts.fail} fail, ${report.counts.needsReview} need review).<br>
  Uncertainty band ${lo}–${hi}% once “needs review” items are resolved by a human.${report.jevMs != null ? " Jev adjudicated judgement calls." : ""}</div></div>
  <h2>Failures and items needing human review (${actionable.length})</h2>
  ${actionable.length > 0 ? `<table><thead><tr><th></th><th>Criterion</th><th>Level</th><th>Conf.</th><th>Finding</th></tr></thead><tbody>${rows}</tbody></table>`
    : "<p>No failures or review items — all checked criteria passed.</p>"}
  <h2>Method</h2>
  <p>Deterministic checks via axe-core ${esc(axeBit)}; semantic judgement calls via one Jev evaluation.
  Automated testing catches roughly a third of barriers — “needs review” items require a human, ideally with assistive technology.</p>
  <div class="foot">Generated by Jev WCAG Auditor · ${esc(report.id)} · Full interactive report available in the app.</div>
</body></html>`;

  return new NextResponse(html, { headers: { "Content-Type": "text/html; charset=utf-8" } });
}
